### ISSUE TITLE
mDirectionPin==NO_DIR_PORT

### ISSUE THREAD

**Issue by sonelu** [descampsa/ardyno#1]
Hi,

In DynamixelInterface.h lines 24 and 37, shouldn't be

`		if(mDirectionPin!=NO_DIR_PORT)`

instead of:
`		if(mDirectionPin==NO_DIR_PORT)`

**Comment by descampsa** [comment]
You are right, thanks for reporting it.
I had actually a fix in my local repository, but had forgotten to push it. 

Let know if it works correctly for you now.
